import type { Metadata } from "next";
import { Raleway, Ramabhadra, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/common/Navbar";
import HeaderBar from "./components/common/HeaderBar";
import React from "react";
import Footer from "./components/common/Footer";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "../context/AuthContext";

// Raleway font configuration
const raleway = Raleway({
  variable: "--font-raleway", // Custom CSS variable
  subsets: ["latin"], // Optional: subsets to load
  weight: ["400", "500", "600", "700"], // Optional: specify the font weights you want
  display: "swap", // Optional: defines how the font is displayed
});

// Ramabhadra font configuration
const ramabhadra = Ramabhadra({
  variable: "--font-ramabhadra", // Custom CSS variable
  subsets: ["latin"], // Optional: subsets to load
  weight: ["400"], // Choose the weights you need
  display: "swap", // Optional: defines how the font is displayed
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans", // Custom CSS variable
  subsets: ["latin"], // Optional: subsets to load
  weight: ["400", "500", "600"], // Optional: specify the font weights you want
});

export const metadata: Metadata = {
  title: "The Herb Culture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${ramabhadra.variable} ${dmSans.variable} antialiased font-[raleway]`}
      >
        <AuthProvider>
          <HeaderBar />
          <Navbar />
          {children}
          <ToastContainer
            rtl={false}
            autoClose={2000}
            newestOnTop={true}
            position="top-right"
            hideProgressBar={false}
          />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
